name: frontend
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # state management
  get: ^4.7.2
  
  # utils
  dio: ^5.3.2
  jiffy: ^6.3.2
  uuid: ^4.5.2
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  
  # ui
  cupertino_icons: ^1.0.8
  data_table_2: ^2.5.10
  google_fonts: ^6.3.2
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  file_picker: ^10.3.3
  fl_chart: ^1.1.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^2.0.1
  toastification: ^3.0.3
  cached_network_image: ^3.4.1
  shimmer_animation: ^2.2.2+1
  flutter_easyloading: ^3.0.5
  awesome_dialog: ^3.3.0
  rive: ^0.14.0
  easy_stepper: ^1.0.1
  font_awesome_flutter: ^10.12.0
  
  # supabase
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/fonts/

  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/fonts/Font-Awesome-7-Brands-Regular-400.otf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/Font-Awesome-7-Free-Regular-400.otf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/Font-Awesome-7-Free-Solid-900.otf
          weight: 900
get_cli:
  sub_folder: false